modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="sakalti"
version="1.0.0"
displayName="TConX"
authors="お方"
description='''
TConXはテスト用MODです。Forge 1.16.5対応。
'''
displayURL="https://github.com/maikuran/Tconx"

[[dependencies.sakalti]]
modId="forge"
mandatory=true
versionRange="[36,37)"
ordering="NONE"
side="BOTH"

[[dependencies.sakalti]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"

[[dependencies.sakalti]]
modId="mantle"
mandatory=true
versionRange="[1.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sakalti]]
modId="tconstruct"
mandatory=true
versionRange="[3.3,)"
ordering="AFTER"
side="BOTH"
