modLoader="javafml"
loaderVersion="[36,37)"
license="MIT"

[[mods]]
modId="sakalti2"
version="1.0.0"
displayName="Sakalti2"
authors="Sakalti"
description="Alloying!"

[[dependencies.sakalti2]]
modId="forge"
mandatory=true
versionRange="[36,37)"
ordering="NONE"
side="BOTH"

[[dependencies.sakalti2]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"

[[dependencies.sakalti2]]
modId="tconstruct"
mandatory=true
versionRange="[3.3,)"
ordering="AFTER"
side="BOTH"


[[dependencies.sakalti2]]
modId="constructsarmory"
mandatory=false
versionRange="[2.0.0-alpha.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sakalti2]]
modId="tdelight"
mandatory=false
versionRange="[1.16-1.8,)"
ordering="AFTER"
side="BOTH"
